version: '3.8'

services:
  main:
    build:
      context: .
      dockerfile: docker/Dockerfile.main
    ports:
      - "8000:8000"
    depends_on:
      - stt
      - llm
      - tts
      - render
      - redis
    environment:
      - STT_SERVICE_URL=http://stt:5000
      - LLM_SERVICE_URL=http://llm:5001
      - TTS_SERVICE_URL=http://tts:5002
      - RENDER_SERVICE_URL=http://render:5003
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./models:/app/models

  stt:
    build:
      context: .
      dockerfile: docker/Dockerfile.stt
    expose:
      - 5000
    volumes:
      - ./models/stt:/app/models/stt

  llm:
    build:
      context: .
      dockerfile: docker/Dockerfile.llm
    expose:
      - 5001
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  tts:
    build:
      context: .
      dockerfile: docker/Dockerfile.tts
    expose:
      - 5002
    volumes:
      - ./models/tts:/app/models/tts

  render:
    build:
      context: .
      dockerfile: docker/Dockerfile.render
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    expose:
      - 5003
    volumes:
      - ./models/3d_gs:/app/models/3d_gs

  redis:
    image: redis:6.2-alpine
    expose:
      - 6379
    volumes:
      - redis_data:/data

  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    ports:
      - "3000:3000"
    depends_on:
      - main

volumes:
  redis_data:

networks:
  default:
    driver: bridge